name: 构建 & 推送 Docker 镜像

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  IMAGE_NAME: xiaoyululu/mslx-daemon

jobs:
  build-and-push:
    name: 构建 & 推送 Docker 镜像
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 获取元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # 自动生成 latest
            type=raw,value=latest
            # 自动把 git tag (v0.5.3.1) 解析为 0.5.3.1
            type=ref,event=tag
            # 如果是手动触发，就用 dev
            type=raw,value=dev,enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: 构建并推送
        uses: docker/build-push-action@v5
        with:
          # 上下文目录 (根目录)
          context: .
          # Dockerfile 的位置
          file: ./MSLX.Daemon/Dockerfile
          # 同时构建 x64 和 arm64
          platforms: linux/amd64,linux/arm64
          # 推送开关
          push: true
          # 使用上面生成的标签
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}